definitions:
  request.CreateInvoiceRequest:
    properties:
      paidAmount:
        type: integer
      paidDueDate:
        type: string
      partnerCompanyID:
        type: string
    required:
    - paidAmount
    - paidDueDate
    - partnerCompanyID
    type: object
  response.GetInvoicesResponse:
    properties:
      invoices:
        items:
          $ref: '#/definitions/response.getInvoiceResponseItem'
        type: array
    type: object
  response.PostResponse:
    properties:
      ok:
        type: integer
    type: object
  response.getInvoiceResponseItem:
    properties:
      billedAmount:
        type: integer
      commission:
        type: integer
      id:
        type: string
      invoiceStatus:
        type: string
      paidAmount:
        type: integer
      paidDueDate:
        type: string
      partnerCompanyBankAccount:
        $ref: '#/definitions/response.partnerCompanyBankAccountResponse'
      partnerCompanyID:
        type: string
      partnerCompanyName:
        type: string
      publishedDate:
        type: string
      tax:
        type: integer
    type: object
  response.partnerCompanyBankAccountResponse:
    properties:
      accountHolderName:
        type: string
      accountNumber:
        type: string
      accountType:
        type: string
      bankName:
        type: string
      branchName:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/invoices:
    get:
      description: |-
        ⚫︎パラメータについて: <br> 「startDate」支払い期日で絞り込む時の開始日時 フォーマットはRFC3339の文字列(例:日本時間22時の場合 "2025-05-31T22:00:00+09:00") <br> 「endDate」支払い期日で絞り込む時の終了日時 フォーマットはRFC3339の文字列(例:日本時間22時の場合 "2025-05-31T22:00:00+09:00")
        ⚫︎レスポンスについて: <br> 「paidDueDate」: 支払い期日 フォーマットはRFC3339の文字列, 「publishedDate」: Dateのみ(時間は無し), <br>「paidAmount」: 支払い金額, 　「billedAmount」: 請求金額(支払金額 に手数料4%を加えたものに更に手数料の消費税を加えたもの),  <br>「partnerCompanyBankAccount」: 取引先の口座情報
        ⚫︎説明: <br> ログイン中のユーザー情報を取得し、そのユーザーが所属する企業が登録した請求書一覧を取得するAPI
      parameters:
      - in: query
        name: endDate
        type: string
      - in: query
        name: startDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetInvoicesResponse'
      security:
      - DebugUser: []
        Token: []
      summary: 請求書 取得
      tags:
      - invoice
    post:
      description: |-
        ⚫︎パラメータについて: <br> 「paidDueDate」支払い期日 フォーマットはRFC3339の文字列(例:日本時間22時の場合 "2025-05-31T22:00:00+09:00") <br> 「partnerCompnayID」: 取引先ID <br> 「paidAmount」: 支払い金額
        ⚫︎説明: <br> ログイン中のユーザー情報を取得し、そのユーザーが所属する企業の取引先企業への支払いについての請求書を登録するAPI
      parameters:
      - description: ' '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateInvoiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PostResponse'
      security:
      - DebugUser: []
        Token: []
      summary: 請求書 登録
      tags:
      - invoice
swagger: "2.0"
