definitions:
  request.CreateInvoiceRequest:
    properties:
      paidAmount:
        type: integer
      paidDueDate:
        type: string
      partnerCompanyID:
        type: string
    required:
    - paidAmount
    - paidDueDate
    - partnerCompanyID
    type: object
  response.PostResponse:
    properties:
      ok:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/invoices:
    post:
      description: |-
        ⚫︎パラメータについて: <br> 「paidDueDate」支払い期日 フォーマットはRFC3339の文字列(例:日本時間22時の場合 "2025-05-31T22:00:00+09:00") <br> 「partnerCompnayID」: 取引先ID <br> 「paidAmount」: 支払い金額
        ⚫︎説明: <br> ログイン中のユーザー情報を取得し、そのユーザーが所属する企業の取引先企業への支払いについての請求書を登録するAPI
      parameters:
      - description: ' '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateInvoiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PostResponse'
      security:
      - DebugUser: []
        Token: []
      summary: 請求書 登録
      tags:
      - invoice
swagger: "2.0"
